# This is a basic workflow to help you get started with Actions

name: Store transactions

# Controls when the workflow will run
on:
  schedule:
    - cron: "07 */24 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Use deno
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      # Runs a set of commands using the runners shell
      - name: Main program
        run: |
          echo "🤖 Executing fetcher..."
          deno run --allow-net=ob.nordigen.com/,api.notion.com,api.coinbase.com --allow-env ./src/main.ts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          COINBASE_KEY: ${{ secrets.COINBASE_KEY }}
          COINBASE_SECRET: ${{ secrets.COINBASE_SECRET }}
          NORDIGEN_SECRET: ${{ secrets.NORDIGEN_SECRET }}
          NORDIGEN_KEY: ${{ secrets.NORDIGEN_KEY }}
